AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Globals:
  Api:
    Cors: "'194.176.64.84'"
    MethodSettings: [{
      # Turn on Info logging
#      "LoggingLevel": "INFO",

      # Enable Metrics
#      "MetricsEnabled": True,

      "ThrottlingBurstLimit": 5,
      "ThrottlingRateLimit": 10,

      # On all Paths & methods
      "ResourcePath": "/*",
      "HttpMethod": "*",
    }]

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        info:
          description: "We service API test/development"
          version: "1.0.0"
          title:
            Ref: AWS::StackName
        basePath: "/"
        schemes:
        - "http"
        x-amazon-apigateway-request-validators :
          full:
            validateRequestBody: true
            validateRequestParameters: true
          body-only:
            validateRequestBody: true
            validateRequestParameters: false
        x-amazon-apigateway-request-validator: "full"
        paths:
          "/prospect":
            post:
              tags:
              - "prospect"
              summary: "Create a prospect"
              operationId: "addProspect"
              consumes:
              - "application/json"
              produces:
              - "application/json"
              x-amazon-apigateway-request-validator: "body-only"
              parameters:
              - in: "body"
                name: "body"
                description: "Prospect object to be saved to OGI"
                required: true
                schema:
                  $ref: "#/definitions/Prospect"
              responses:
                '200':
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy

                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProspectFunction.Arn}/invocations
          "/risk":
            post:
              tags:
              - "risk"
              summary: "Add policy risk to a prospect"
              operationId: "addRisk"
              consumes:
              - "application/json"
              produces:
              - "application/json"
              x-amazon-apigateway-request-validator: "body-only"
              parameters:
              - in: "body"
                name: "body"
                description: "Risk object to saved to a prospect"
                required: true
                schema:
                  $ref: "#/definitions/Risk"
              responses:
                '200':
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RiskFunction.Arn}/invocations
        definitions:
          Prospect:
            type: "object"
            additionalProperties:
              False
            required:
            - "Name"
            - "Pcode"
            - "Email"
            - "Tel"
            - "Addr1"
            properties:
              Name:
                type: "string"
                minLength: 1
                maxLength: 30
              Pcode:
                type: "string"
                minLength: 6
                maxLength: 9
              Email:
                type: "string"
                minLength: 1
                maxLength: 50
              Tel:
                type: "string"
                minLength: 1
                maxLength: 20
              Addr1:
                type: "string"
                minLength: 1
                maxLength: 30
              Addr2:
                type: "string"
                minLength: 1
                maxLength: 30
              Addr3:
                type: "string"
                minLength: 1
                maxLength: 30
              Addr4:
                type: "string"
                minLength: 1
                maxLength: 30
          ProspectResponse:
            type: "object"
            properties:
              Refno:
                type: "string"
              message:
                type: "string"
          Risk:
            type: "object"
            additionalProperties:
              False
            required:
            - "Ptype"
            - "Risk"
            - "Refno"
            properties:
              Refno:
                type: "string"
                minLength: 1
                maxLength: 7
              Ptype:
                type: "string"
                enum: ["DG", "PT", "PM"]
              Risk:
                type: "object"
                additionalProperties:
                  False
                required:
                - "RsFrame"
                - "RsFrame2"
                properties:
                  RsFrame:
                    type: "object"
                    additionalProperties:
                      False
                    properties:
                      indemLvl:
                        type: "string"
                      pubLib:
                        type: "string"
                  RsFrame2:
                    type: "object"
                    additionalProperties:
                      False
                    properties:
                      indemLvl:
                        type: "string"
                      pubLib:
                        type: "string"
          RiskResponse:
            type: "object"
            properties:
              Refno:
                type: "string"
              Polref:
                type: "string"
              Premium:
                type: "string"
              message:
                type: "string"
  ProspectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: prospect_handler.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /prospect
            Method: post
  RiskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: risk_handler.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /risk
            Method: post