AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Globals:
  Api:
    Cors: "'www.dave.com'"
    MethodSettings: [{
      # Turn on Info logging
#      "LoggingLevel": "INFO",

      # Enable Metrics
#      "MetricsEnabled": True,

      "ThrottlingBurstLimit": 5,
      "ThrottlingRateLimit": 10,

      # On all Paths & methods
      "ResourcePath": "/*",
      "HttpMethod": "*",
    }]

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          # Replace <bucket> with your bucket name
          Parameters:
            Location: s3://aws-codestar-us-east-1-853044416690-pythonlambdates-pipe/pythonlambdates-Pipe/pythonlamb/swagger.yaml
  ProspectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: prospect_handler.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /prospect
            Method: post
  RiskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: risk_handler.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /risk
            Method: post